import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, BrainCircuit, Leaf, Plus, RotateCcw, Save, Zap, TrendingUp, Target, CircleGauge, ArrowDownRight, ArrowRight, Database } from 'lucide-react';
import { defaultData } from './data/electricityData';
import { mean, variance, standardDeviation } from './utils/statistics';
import { regression, predictValue } from './utils/regression';
import Sidebar from './components/Sidebar';
import Navbar from './components/Navbar';
import StatCard from './components/StatCard';
import RegressionChart from './components/RegressionChart';
import DataTable from './components/DataTable';
import FormulaCard from './components/FormulaCard';

const fmt = (value, digits = 2) => Number(value).toFixed(digits);
const getSaved = () => { try { const saved = localStorage.getItem('ecopredict-data'); return saved ? JSON.parse(saved) : defaultData; } catch { return defaultData; } };

function Landing({ setPage }) { return <main className="landing"><nav className="landing-nav"><button className="brand"><span>⚡</span><b>EcoPredict</b></button><button className="text-button" onClick={() => setPage('about')}>About project</button></nav><section className="hero"><div className="hero-copy"><span className="pill"><i/> SIMPLE LINEAR REGRESSION</span><h1>See the pattern.<br/><em>Predict the power.</em></h1><p>Analyze electricity usage patterns and predict future consumption using a clear, explainable regression model.</p><div className="hero-actions"><button className="primary-btn" onClick={() => setPage('dashboard')}>Explore dashboard <ArrowRight size={18}/></button><button className="secondary-btn" onClick={() => setPage('prediction')}>Predict consumption</button></div><div className="hero-proof"><span>✦</span> Built for understanding, not just calculating.</div></div><div className="energy-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="energy-core"><Zap size={58} fill="currentColor"/><b>ENERGY</b><small>INSIGHT</small></div><div className="float-card card-top"><TrendingUp/><div><small>MODEL FIT</small><b>Strong positive</b></div></div><div className="float-card card-bottom"><Leaf/><div><small>FOCUS</small><b>Smarter usage</b></div></div></div></section><section className="features">{[[BarChart3,'Data analysis','Explore historical appliance usage and consumption patterns.'],[BrainCircuit,'Regression model','Turn real observations into an explainable equation.'],[Target,'Prediction','Estimate future electricity consumption with confidence.']].map(([Icon,title,text]) => <article key={title}><div><Icon size={22}/></div><h3>{title}</h3><p>{text}</p></article>)}</section></main> }

function Dashboard({ data, model, setPage, setOpen }) { return <><Navbar title="Electricity Consumption Analytics" subtitle="A live view of your educational energy dataset." setOpen={() => setOpen(true)}/><main className="page-content"><section className="stats-grid"><StatCard icon={Activity} label="Average usage hours" value={`${fmt(model.meanX,1)} h/day`} detail="Across all observations"/><StatCard icon={Zap} label="Average consumption" value={`${fmt(model.meanY,1)} kWh`} detail="Daily electricity use" accent="blue"/><StatCard icon={TrendingUp} label="Correlation" value={fmt(model.correlation)} detail={model.correlation > .7 ? 'Strong positive relationship' : 'Linear relationship'} accent="orange"/><StatCard icon={Target} label="Model accuracy / R²" value={`${fmt(model.rSquared * 100,1)}%`} detail="Variation explained" accent="purple"/></section><section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">DATA RELATIONSHIP</span><h2>Usage vs. electricity consumption</h2></div><span className="live-dot">LIVE MODEL</span></div><RegressionChart data={data} model={model}/></article><article className="insight-card"><div className="insight-icon"><BrainCircuit size={25}/></div><span className="eyebrow">REGRESSION INSIGHT</span><h2>The relationship is moving <em>upward.</em></h2><p>Every additional appliance-use hour is associated with approximately <b>{fmt(model.slope)} kWh</b> more daily consumption in this dataset.</p><div className="equation-mini">y = {fmt(model.intercept)} + {fmt(model.slope)}x</div><button className="link-btn" onClick={() => setPage('model')}>See how we calculate this <ArrowRight size={16}/></button></article></section><section className="panel quick-section"><div><span className="eyebrow">QUICK START</span><h2>Ready to model a future usage day?</h2><p>Enter appliance usage hours and let the fitted regression line estimate consumption.</p></div><button className="primary-btn" onClick={() => setPage('prediction')}>Make a prediction <SparkleIcon/></button></section></main></> }
function SparkleIcon(){ return <Zap size={17}/> }

function Analysis({ data, model, setOpen }) { const x = model.x, y = model.y; const cards = [['Observations',data.length],['Mean usage',`${fmt(mean(x))} h`],['Mean consumption',`${fmt(mean(y))} kWh`],['Usage range',`${fmt(Math.min(...x),1)} – ${fmt(Math.max(...x),1)} h`],['Consumption range',`${fmt(Math.min(...y),1)} – ${fmt(Math.max(...y),1)} kWh`],['Variance (X / Y)',`${fmt(variance(x))} / ${fmt(variance(y))}`],['Std. deviation (X)',fmt(standardDeviation(x))],['Std. deviation (Y)',fmt(standardDeviation(y))]]; return <><Navbar title="Data Analysis" subtitle="Explore the observations used to fit the model." setOpen={() => setOpen(true)}/><main className="page-content"><section className="analysis-grid">{cards.map(([label,value])=><article className="metric" key={label}><span>{label}</span><b>{value}</b></article>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">OBSERVED DATA</span><h2>Consumption follows usage</h2></div></div><RegressionChart data={data} model={model} height={380}/></section><section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">EDUCATIONAL SYNTHETIC DATASET</span><h2>Historical observations</h2></div></div><DataTable data={data}/></section></main></> }

function Model({ model, setOpen }) { const sign = model.slope >= 0 ? '+' : '−'; return <><Navbar title="Regression Model" subtitle="Every result is calculated directly from your dataset." setOpen={() => setOpen(true)}/><main className="page-content"><section className="model-hero"><div><span className="eyebrow">SIMPLE LINEAR REGRESSION</span><h2>y = a + bx</h2><p>Fitted equation: <b>y = {fmt(model.intercept)} {sign} {fmt(Math.abs(model.slope))}x</b></p></div><div className="model-score"><CircleGauge/><span>R² score</span><b>{fmt(model.rSquared * 100,1)}%</b></div></section><section className="model-values">{[['Mean X',`${fmt(model.meanX)} hours`],['Mean Y',`${fmt(model.meanY)} kWh`],['Slope (b)',fmt(model.slope)],['Intercept (a)',fmt(model.intercept)],['Pearson r',fmt(model.correlation)],['R²',fmt(model.rSquared)]].map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</section><section className="calculation"><div className="section-title"><span className="eyebrow">CALCULATION DETAILS</span><h2>Follow the mathematics, step by step</h2><p>These values update automatically whenever the dataset changes.</p></div><div className="formula-grid"><FormulaCard title="STEP 1 · MEAN OF X" formula="x̄ = Σx / n">x̄ = {fmt(model.x.reduce((s,v)=>s+v,0))} / {model.x.length} = <b>{fmt(model.meanX)}</b></FormulaCard><FormulaCard title="STEP 2 · MEAN OF Y" formula="ȳ = Σy / n">ȳ = {fmt(model.y.reduce((s,v)=>s+v,0))} / {model.y.length} = <b>{fmt(model.meanY)}</b></FormulaCard><FormulaCard title="STEP 3 · SLOPE" formula="b = Σ(x − x̄)(y − ȳ) / Σ(x − x̄)²">b = {fmt(model.numerator)} / {fmt(model.denominator)} = <b>{fmt(model.slope)}</b></FormulaCard><FormulaCard title="STEP 4 · INTERCEPT" formula="a = ȳ − bx̄">a = {fmt(model.meanY)} − ({fmt(model.slope)} × {fmt(model.meanX)}) = <b>{fmt(model.intercept)}</b></FormulaCard><FormulaCard title="STEP 5 · EQUATION" formula="y = a + bx">y = {fmt(model.intercept)} + {fmt(model.slope)}x</FormulaCard><FormulaCard title="STEP 6 · PREDICTION" formula="ŷ = a + bx">Use any usage value x to estimate electricity consumption ŷ.</FormulaCard></div></section></main></> }

function Prediction({ data, model }) { const [usage,setUsage] = useState(8); const prediction = predictValue(usage,model.slope,model.intercept); return <><Navbar title="Predict Electricity Consumption" subtitle="Use the fitted model to estimate a future day." setOpen={()=>{}}/><main className="page-content"><section className="predict-layout"><article className="prediction-form"><span className="eyebrow">MODEL-BASED ESTIMATE</span><h2>How long will appliances run?</h2><p>Enter daily appliance usage hours to generate an estimated consumption value.</p><label>Appliance usage hours <input type="number" min="0" step="0.5" value={usage} onChange={e=>setUsage(e.target.value)}/><small>Hours per day</small></label><div className="prediction-result"><span>Predicted consumption</span><b>{fmt(prediction)} <em>kWh/day</em></b><p>For <strong>{usage} hours</strong> of usage, the model estimates approximately <strong>{fmt(prediction)} kWh/day</strong>.</p></div><div className="equation-note">ŷ = {fmt(model.intercept)} + ({fmt(model.slope)} × {usage})</div></article><article className="panel prediction-chart"><div className="panel-head"><div><span className="eyebrow">PREDICTION VISUALIZATION</span><h2>Your point on the trend</h2></div></div><RegressionChart data={data} model={model} prediction={{usage,value:prediction}} height={400}/></article></section></main></> }

function WhatIf({ model }) { const [current,setCurrent]=useState(8), [proposed,setProposed]=useState(6); const currentValue=predictValue(current,model.slope,model.intercept), proposedValue=predictValue(proposed,model.slope,model.intercept), difference=currentValue-proposedValue; return <><Navbar title="What-If Energy Analysis" subtitle="Compare usage scenarios through the fitted linear model." setOpen={()=>{}}/><main className="page-content"><section className="whatif-card"><div className="section-title"><span className="eyebrow">SCENARIO EXPLORER</span><h2>See the impact before you change a habit.</h2></div><div className="scenario-inputs"><label>Current daily usage<input type="number" min="0" step="0.5" value={current} onChange={e=>setCurrent(e.target.value)}/><span>hours/day</span></label><ArrowDownRight/><label>Proposed daily usage<input type="number" min="0" step="0.5" value={proposed} onChange={e=>setProposed(e.target.value)}/><span>hours/day</span></label></div><div className="scenario-results"><article><span>CURRENT ESTIMATE</span><b>{fmt(currentValue)} <em>kWh/day</em></b></article><article className={difference >= 0 ? 'saving' : 'increase'}><span>{difference >= 0 ? 'ESTIMATED REDUCTION' : 'ESTIMATED INCREASE'}</span><b>{fmt(Math.abs(difference))} <em>kWh/day</em></b></article><article><span>PROPOSED ESTIMATE</span><b>{fmt(proposedValue)} <em>kWh/day</em></b></article></div><p className="disclaimer">Reducing usage from {current} to {proposed} hours is associated with an estimated {Math.abs(difference).toFixed(2)} kWh/day {difference >= 0 ? 'reduction' : 'increase'} according to this regression model. This is a model-based estimate, not a guarantee.</p></section></main></> }

function Dataset({ data, setData }) { const [draft,setDraft]=useState({usage:'',consumption:''}), [editing,setEditing]=useState(null); const save = e => {e.preventDefault(); if(!draft.usage || !draft.consumption) return; if(editing) setData(data.map(row=>row.id===editing?{...row,usage:Number(draft.usage),consumption:Number(draft.consumption)}:row)); else setData([...data,{id:Date.now(),usage:Number(draft.usage),consumption:Number(draft.consumption)}]); setDraft({usage:'',consumption:''}); setEditing(null);}; const edit=row=>{setEditing(row.id);setDraft({usage:row.usage,consumption:row.consumption})}; return <><Navbar title="Dataset" subtitle="Manage the synthetic observations behind the regression model." setOpen={()=>{}}/><main className="page-content"><section className="dataset-top"><div className="dataset-note"><Database/><div><span className="eyebrow">EDUCATIONAL SYNTHETIC DATASET</span><h2>Shape the model with your observations.</h2><p>This dataset is created for education and does not represent a real household or company.</p></div></div><button className="secondary-btn reset" onClick={()=>setData(defaultData)}><RotateCcw size={16}/> Reset dataset</button></section><section className="dataset-layout"><article className="panel table-panel"><DataTable data={data} editable onEdit={edit} onDelete={id=>setData(data.filter(row=>row.id!==id))}/></article><form className="add-form" onSubmit={save}><span className="eyebrow">{editing?'EDIT OBSERVATION':'ADD OBSERVATION'}</span><h2>{editing?'Update data row':'Add data to the model'}</h2><label>Appliance usage hours<input required type="number" min="0" step="0.1" value={draft.usage} onChange={e=>setDraft({...draft,usage:e.target.value})}/></label><label>Electricity consumption (kWh)<input required type="number" min="0" step="0.1" value={draft.consumption} onChange={e=>setDraft({...draft,consumption:e.target.value})}/></label><button className="primary-btn" type="submit">{editing?<Save size={17}/> : <Plus size={17}/>}{editing?'Save changes':'Add observation'}</button>{editing&&<button type="button" className="text-button" onClick={()=>{setEditing(null);setDraft({usage:'',consumption:''})}}>Cancel edit</button>}</form></section></main></> }

function About(){return <><Navbar title="About EcoPredict" subtitle="An academic demonstration of Simple Linear Regression." setOpen={()=>{}}/><main className="page-content"><section className="about-hero"><span className="eyebrow">B.TECH PROBABILITY & STATISTICS PROJECT</span><h2>Energy decisions become clearer when the math is visible.</h2><p>Electricity consumption varies with appliance usage and many other factors. EcoPredict uses a focused Simple Linear Regression model to understand the relationship and predict consumption from usage hours.</p></section><section className="about-grid"><FormulaCard title="PROBLEM STATEMENT" formula="Usage → consumption">Understanding the relationship between usage and consumption can help users make better energy decisions.</FormulaCard><FormulaCard title="PROPOSED SOLUTION" formula="y = a + bx">EcoPredict analyzes historical educational data and predicts consumption based on appliance usage hours.</FormulaCard><FormulaCard title="SYLLABUS CONCEPT USED" formula="Module X — Regression">The project applies only Simple Linear Regression: an independent variable x, a dependent variable y, intercept a, and slope b.</FormulaCard></section><section className="panel real-world"><span className="eyebrow">REAL-WORLD USE</span><h2>What this model can help illustrate</h2><div>{['Understanding energy consumption','Predicting electricity usage','Comparing different usage patterns','Supporting energy planning','Identifying potential reductions','Data-driven decision making'].map(item=><p key={item}><Leaf size={16}/>{item}</p>)}</div><small>This is an educational prediction model. Actual electricity consumption depends on many factors beyond appliance usage hours.</small></section></main></>}

export default function App(){ const [data,setData]=useState(getSaved); const [page,setPage]=useState('landing'); const [open,setOpen]=useState(false); useEffect(()=>localStorage.setItem('ecopredict-data',JSON.stringify(data)),[data]); const model=useMemo(()=>regression(data),[data]); const props={data,model,setData,setPage,setOpen}; const screens={landing:<Landing setPage={setPage}/>,dashboard:<Dashboard {...props}/>,analysis:<Analysis {...props}/>,model:<Model {...props}/>,prediction:<Prediction {...props}/>,whatif:<WhatIf {...props}/>,dataset:<Dataset {...props}/>,about:<About {...props}/>}; if(page==='landing') return screens.landing; return <div className="app-shell"><Sidebar page={page} setPage={setPage} open={open} setOpen={setOpen}/><div className="content-area">{screens[page]}</div></div> }
